apiVersion: apps/v1
kind: Deployment
metadata:
  name: teedy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teedy
  template:
    metadata:
      labels:
        app: teedy
    spec:
      containers:
      - name: teedy
        image: nerleta09/teedy_ina_manual:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teedy-service
spec:
  type: LoadBalancer
  selector:
    app: teedy
  ports:
  - port: 8080
    targetPort: 8080