insert into T_CONFIG(CFG_ID_C, CFG_VALUE_C) values('GUEST_LOGIN', 'true');
insert into T_USER(USE_ID_C, USE_IDROLE_C, USE_USERNAME_C, USE_PASSWORD_C, USE_EMAIL_C, USE_CREATEDATE_D, USE_PRIVATEKEY_C) values('guest', 'user', 'guest', '', 'guest@localhost', NOW(), 'GuestPk');

CREATE CACHED TABLE T_USER_REQUEST (
    REQ_ID_C VARCHAR(36) NOT NULL,
    REQ_USERNAME_C VARCHAR(50) NOT NULL,
    REQ_EMAIL_C VARCHAR(100) NOT NULL,
    REQ_PASSWORD_C VARCHAR(60) NOT NULL,
    REQ_STATUS_C VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    REQ_CREATEDATE_D DATETIME DEFAULT NOW() NOT NULL,
    PRIMARY KEY (REQ_ID_C)
);

update T_CONFIG set CFG_VALUE_C = '10' where CFG_ID_C = 'DB_VERSION';
